import type { NextPage } from "next"
import Head from "next/head"
import { useEffect, useState } from "react"
import BeerList from "../components/BeerList"
import Pagination from "../components/Pagination"

const Home: NextPage = () => {
  const [beerList, setBeerList] = useState([])
  const [loading, setLoading] = useState(false)
  const [currentPage, setCurrentPage] = useState(1)
  const [beersPerPage, setBeersPerPage] = useState(6)
  const [inititalBeerList, setInitialBeerList] = useState([])

  useEffect(() => {
    const getBeers = async () => {
      setLoading(true)
      const res = await fetch("https://api.punkapi.com/v2/beers")
      const data = await res.json()
      setBeerList(data)
      setLoading(false)
      setInitialBeerList(data)
    }

    getBeers()
  }, [])

  // Get Current BEERS
  const indexOfLastBeer = currentPage * beersPerPage
  const indexOfFirstBeer = indexOfLastBeer - beersPerPage
  const currentBeers = beerList.slice(indexOfFirstBeer, indexOfLastBeer)

  // PAGE SELECT
  const selectPage = (pageNumber: number) => {
    setCurrentPage(pageNumber)
  }

  // SEARCH
  const handleSearch = (e: any) => {
    const searchWord = e.target.value.toLowerCase()

    const filteredList: any = inititalBeerList.filter((beer: any) => {
      const beerName = beer.name.toLowerCase()
      if (searchWord && beerName.includes(searchWord)) {
        return beer
      }
    })

    if (searchWord === "") {
      setBeerList(inititalBeerList)
    } else {
      setBeerList(filteredList)
    }
  }

  return (
    <>
      <Head>
        <title>Beer Finder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-start h-screen p-4 pb-10">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Beer Finder
        </h1>
        <input
          onChange={handleSearch}
          className="w-1/2 h-12 py-2 border-2 border-black pl-4"
          placeholder="Type the name of the beer"
        ></input>
        <BeerList beerList={currentBeers} loading={loading}></BeerList>
        <Pagination
          beersPerPage={beersPerPage}
          totalBeers={beerList.length}
          selectPage={selectPage}
          activePage={currentPage}
        ></Pagination>
      </main>
    </>
  )
}

export default Home
